# Generated by Django 3.1.7 on 2021-04-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftme', '0002_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка'),
        ),
    ]
