# Generated by Django 3.1.7 on 2021-04-26 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giftme', '0003_auto_20210404_0929'),
        ('giftme', '0003_auto_20210426_1438'),
    ]

    operations = [
    ]
